language: generic
cache:
  directories:
    - /home/travis/.emacs.d/elpa/
    - /tmp/emacs
sudo: false
env:
  global:
    - EMACS_VERSION=26.2
    - EMACS_INSTALL_DIRECTORY=/emacs/$EMACS_VERSION
install: make install_dependencies
script: make publish-blog
deploy:
  provider: pages
  local_dir: build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
