language: generic
cache:
  directories:
    - /home/travis/.emacs.d/elpa/
sudo: false
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=26.2
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
script:
  make publish-blog
deploy:
  provider: pages
  local_dir: build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
