language: minimal
cache:
  directories:
    - /home/travis/.emacs.d/elpa/
sudo: false
install: make install_dependencies
script:
  - export PATH="${EMACS_INSTALL_DIRECTORY}/tmp/emacs/bin:$PATH"
  - make publish-blog
deploy:
  provider: script
  script: make deploy-blog
  on:
    branch: master
