language: minimal
cache:
  directories:
    - /home/travis/.emacs.d/elpa/
sudo: false
env:
  matrix:
    - EMACS_VERSION=26.2
install:
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export PATH=/tmp/emacs/bin:${PATH}
script:
  - export PATH="${EMACS_INSTALL_DIRECTORY}/tmp/emacs/bin:$PATH"
  - make publish_blog
deploy:
  provider: pages
  local_dir: build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
