language: generic
cache:
  directories:
    - /home/travis/.emacs.d/elpa/
sudo: false
install: make install_dependencies
script: make publish-blog
deploy:
  provider: pages
  local_dir: build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
